//! Bundled-parser manifest resolution (#100, A2.5 Phase R).
//!
//! The native live-server resolves a parser for a file WITHOUT Python entry points: it reads
//! `parser_manifest.json` (generated by `scripts/gen_parser_manifest.py`) from the bundled wasm
//! directory and maps a file extension → `(language, plugin_id, wasm file)`. This is the
//! extension-based first cut; content-based wasm `detect-language` (for ambiguous/no-extension
//! files) is a later refinement — those fall through to the Python differ for now.

use std::collections::HashMap;
use std::path::Path;
use std::sync::{Arc, Mutex, OnceLock};

use serde::Deserialize;

#[derive(Deserialize)]
struct ParserEntry {
    plugin_id: String,
    wasm: String,
}

#[derive(Deserialize)]
struct Manifest {
    parsers: HashMap<String, ParserEntry>,     // language_id -> entry
    extension_index: HashMap<String, String>,  // ".ext" -> language_id
}

/// A resolved parser for a file. `wasm_path` is "" for the native-Python path (parsed in-core via
/// tree-sitter-python — no wasm needed).
pub(crate) struct ResolvedParser {
    pub language: String,
    pub plugin_id: String,
    pub wasm_path: String,
}

fn manifest_cache() -> &'static Mutex<HashMap<String, Option<Arc<Manifest>>>> {
    static CACHE: OnceLock<Mutex<HashMap<String, Option<Arc<Manifest>>>>> = OnceLock::new();
    CACHE.get_or_init(|| Mutex::new(HashMap::new()))
}

/// Load + cache `<wasm_dir>/parser_manifest.json` (per wasm_dir; the dir is stable per process).
fn load_manifest(wasm_dir: &str) -> Option<Arc<Manifest>> {
    let cache = manifest_cache();
    if let Ok(map) = cache.lock() {
        if let Some(entry) = map.get(wasm_dir) {
            return entry.clone();
        }
    }
    let parsed = std::fs::read_to_string(Path::new(wasm_dir).join("parser_manifest.json"))
        .ok()
        .and_then(|data| serde_json::from_str::<Manifest>(&data).ok())
        .map(Arc::new);
    if let Ok(mut map) = cache.lock() {
        map.insert(wasm_dir.to_owned(), parsed.clone());
    }
    parsed
}

/// Resolve the parser for *path* (by lowercase file extension) using the manifest in *wasm_dir*.
/// Returns `None` for an unknown extension or a missing/invalid manifest → the caller falls back.
pub(crate) fn resolve_parser(path: &str, wasm_dir: &str) -> Option<ResolvedParser> {
    let manifest = load_manifest(wasm_dir)?;
    let ext = Path::new(path)
        .extension()
        .map(|e| format!(".{}", e.to_string_lossy().to_lowercase()));
    // The Python registry NEVER refuses a file: unknown extensions (uv.lock, …) and
    // extension-less names route to the GENERIC line-oriented parser, exactly like
    // `detect_parser`'s fallback. Refusing here was the "no bundled parser" review brick.
    let generic = "generic".to_owned();
    let language = ext
        .as_ref()
        .and_then(|e| manifest.extension_index.get(e))
        .unwrap_or(&generic);
    let entry = manifest.parsers.get(language)?;
    let wasm_path = if language == "python" {
        String::new()
    } else {
        Path::new(wasm_dir)
            .join(&entry.wasm)
            .to_string_lossy()
            .into_owned()
    };
    Some(ResolvedParser {
        language: language.clone(),
        plugin_id: entry.plugin_id.clone(),
        wasm_path,
    })
}
